services:
  app:
    build: .
    container_name: supertl2
    ports:
      - "5000:5000"
    volumes:
      - ./db:/db                                        # mount the database directory
      - ../../statsforstrava/storage/database:/stravadb # mount where the statsforstrava database is stored
      - .:/app                                          # mount the application code
    environment:
      FLASK_ENV: development   # Enables debug mode and auto-reload
      FLASK_DEBUG: 1
      FLASK_APP: apps/backend/supertl2.py
      PYTHONPATH: /app/apps/common
    command: flask run --host=0.0.0.0
